name: ci-dotnet
on:
  pull_request:
    branches:
      - main

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          dotnet-quality: 'preview'

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Installing dotnet-coverage
        run: dotnet tool install -g dotnet-coverage

      - name: Building Application
        run: dotnet build --no-incremental

      - name: Running Tests
        run: dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"

      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: brunogomes99/ci-dotnet-test:latest
      
      - name: Install SonarCloud scanner
        run: dotnet tool install -g dotnet-sonarscanner

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
